Models/Customer.cs
using System.Collections.Generic;

namespace AspNetCorePostgreSQLDockerApp.Models {
  public class Customer
  {
    public int Id { get; set; }
    public string FirstName { get; set; }
    public string LastName { get; set; }
    public string Email { get; set; }
    public string Address { get; set; }
    public string City { get; set; }
    public State State { get; set; }
    public int Zip { get; set; }
    public string Gender { get; set; }
    public int OrderCount { get; set; }
    public List<Order> Orders { get; set; }
  }
}

Models/DockerCommand.cs
using System;
using System.Collections.Generic;

namespace AspNetCorePostgreSQLDockerApp.Models {
  
  public class DockerCommand {
    public int Id { get; set; }
    public string Command { get; set; }
    public string Description { get; set; }
    public List<DockerCommandExample> Examples { get; set; }    
  }
  
}

Models/DockerCommandExample.cs
using System;

namespace AspNetCorePostgreSQLDockerApp.Models {
  
  public class DockerCommandExample {
    public int Id { get; set; }
    public string Example { get; set; }
    public string Description { get; set; }
  }
  
}

Models/Order.cs
namespace AspNetCorePostgreSQLDockerApp.Models {
  public class Order {
    public int Id { get; set; }
    public string Product { get; set; }
    public int Quantity { get; set; }
    public decimal Price { get; set; }
  }
}

Models/State.cs
namespace AspNetCorePostgreSQLDockerApp.Models {
  public class State {
    public int Id { get; set; }
    public string Abbreviation { get; set; }
    public string Name { get; set; }
  }
}

Controllers/CustomersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AspNetCorePostgreSQLDockerApp.Controllers
{
    public class CustomersController : Controller
    {

        public ActionResult Index()
        {
            return View();
        }
    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

using AspNetCorePostgreSQLDockerApp.Repository;

namespace AspNetCorePostgreSQLDockerApp.Controllers
{
    public class HomeController : Controller
    {

        IDockerCommandsRepository _repo;

        public HomeController(IDockerCommandsRepository repo) {
          _repo = repo;
        }

        public async Task<IActionResult> Index()
        {
            //Call into PostgreSQL
            var commands = await _repo.GetDockerCommandsAsync();
            return View(commands);
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        // public IActionResult Error()
        // {
        //     return View();
        // }
    }
}

Views/Customers/Index.cshtml
<link rel="stylesheet" href="css/site.css">

<script src="node_modules/core-js/client/shim.min.js"></script>
<script src="node_modules/zone.js/dist/zone.js"></script>
<script src="node_modules/reflect-metadata/Reflect.js"></script>    
<script src="node_modules/systemjs/dist/system.src.js"></script>

<script src="systemjs.config.js"></script>
<script>
    System.import('app').catch(function(err){ console.error(err); });
</script>
<main class="container">
    <app-container>
        <br />Loading...
    </app-container>
    <br /><br />
</main>

Views/Home/Index.cshtml
@model List<AspNetCorePostgreSQLDockerApp.Models.DockerCommand>
@{
    ViewData["Title"] = "Home Page";
}

<h1>Docker Commands</h1>
From the <a href="https://www.pluralsight.com/courses/docker-web-development">Docker for Web Developers</a> course on Pluralsight.
<br />
<br />
@foreach (var dockerCommand in Model) {

   <h2>@dockerCommand.Command Command</h2>
   @dockerCommand.Description
   <br />
   
   @foreach (var commandExample in dockerCommand.Examples) {
        <h3>@commandExample.Example</h3>
        @commandExample.Description
        <br />
   }
   
   <br />
}

Views/Shared/_Layout.cshtml
<!doctype html>
<html lang="">
    <head>
        <base href="/" />
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - Asp.Net Core PostgreSQL Docker Angular 2 App</title>

        <environment names="Development,Staging,Production">
            <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
                  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
                  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
            <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
        </environment>
    </head>
    <body>
        <div class="navbar navbar-inverse navbar-fixed-top">
            <div class="container">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                        <span class="sr-only">Toggle navigation</span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <a asp-controller="Home" asp-action="Index" class="navbar-brand">ASP.NET Core, PostgreSQL, Docker and Angular 2 App</a>
                </div>
                <div class="navbar-collapse collapse">
                    <ul class="nav navbar-nav">
                        <li><a asp-controller="Home" asp-action="Index">Docker Commands</a></li>
                        <li><a asp-controller="Customers" asp-action="Index">Angular 2</a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <p>&copy; 2016 - Wahlin Consulting</p>
            </footer>
        </div>

        <environment names="Development,Staging,Production">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.1.4.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery">
            </script>
            <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.5/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
            </script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>

        @RenderSection("scripts", required: false)
    </body>
</html>